MollyMaclachlan/website

- pages/contact.html
- pages/home.html
- pages/projects/music.html
- pages/projects/programming.html
- pages/projects/videos.html
- pages/projects/writing.html
- scripts/structures/header.html
- styles/categories/decoration.css
Fixes #25 
Fixes #26 
Fixes #27
> Accessibility fixes

- pages/contact.html
- pages/legal.html
- pages/projects/videos.html
- pages/projects/writing.html
- Update Privacy section of Terms & Service page
- Styling consistency updates.
- Minor text improvements.
- Updated information on Videos and Writing pages.
> Various fixes, improvements and updates.

- scripts/structures/header.html
- styles/categories/decoration.css
- styles/categories/widgets.css
- Fixed focus outline display for tabset links
- Reduced number of nav links leading to the home page
> Further accessibility fixes

- styles/categories/decoration.css
- styles/categories/structure.css
- styles/categories/widgets.css
- styles/main.css
- styles/variables.css
- Fixed focus outline display for tabset links
- Reduced number of nav links leading to the home page
- Improve CSS variable handling
- git do as you're told or you're grounded
> Improve CSS variable handling

- pages/home.html
- Updated Mesa version.
- Changed broken link to say computer page is coming.
> Update computer info on Home page

- styles/categories/structure.css
> Fix footer positioning

- scripts/events.js
- scripts/page_builder.js
- Added themed favicon and logo
- Fixed inaccuracy in comment
Closes #44
> Added themed favicon/logo

- scripts/events.js
- scripts/page_builder.js
- scripts/tabulator.js
- insert_script() should receive the ID as an argument
- Use consistent quotation mark styling in JavaScript
> JavaScript code cleanup

- pages/legal.html
- pages/projects/programming.html
- Corrected a typo
- Added FOSS section to the Programming page
> Added FOSS section to the Programming page

- scripts/events.js
- scripts/structures/header.html
- styles/categories/widgets.css
Descriptions are accessible by the following methods:
- Hovering the eye logo on the left of the navbar
- Focusing the eye logo with the keyboard (it is the second focusable element, directly succeeding the "Skip to main content" link)
- The screen reader should be able to access the description just as it would any other text (it appears in the accessibility tree in inspect element)
> Added descriptions for events that theme the favicon and logo

- scripts/events.js
- scripts/structures/header.html
- styles/categories/widgets.css
- Only make logo focusable if there is a description to show
- Add credit to #logo-container styling
> Only make logo focusable if there is a description to show

- pages/home.html
> Update computer specs

- pages/home.html
- Update computer specs
- Update computer specs last updated date
> Update computer specs (Xfce version -> 4.18)

- pages/accounts.html
- pages/legal.html
This was leading to two issues on these pages:
1. An inability to navigate to the main content using the 'Skip to main content' button.
2. The footer was not locked to the bottom of the page.
> Fix Accounts and Legal pages not containing 'main' element.

- pages/projects/writing.html
- scripts/structures/footer.html
- Update status of 'Rooms of the Desolate'
- Update copyright date
> Further text updates

- pages/home.html
- scripts/structures/header.html
- Update computer specs
- Replace blog link with subreddit link under 'More'
> Replace blog link with subreddit link, under 'More'

- pages/accounts.html
- pages/home.html
- Update Accounts page
- Update computer specs
> Update Accounts page and more

- pages/accounts.html
> Update Accounts page

- pages/home.html
- styles/categories/decoration.css
> Restructure name referencing

- pages/projects/transcribing.html
- styles/categories/decoration.css
- styles/main.css
- styles/variables.css
- Colour management improvements
- Disable pointer events for logo & title
- Enable Bulma 1.0.0
Closes #95
> Upgrade to Bulma 1.0.0

- pages/home.html
This updates the overview description slightly, as well as the computer specs table.
> Update Home page

- README.md
- index.html
- pages/accounts.html
- pages/contact.html
- pages/home.html
- pages/legal.html
- pages/projects/music.html
- pages/projects/programming.html
- pages/projects/programming/github.html
- pages/projects/programming/mods.html
- pages/projects/transcribing.html
- pages/projects/videos.html
- pages/projects/writing.html
- scripts/events.js
- scripts/page_builder.js
- scripts/structures/footer.html
- scripts/structures/header.html
- scripts/theme.js
Switch pronouns to she/her; Murdo to Molly in all plain text contexts; update name etymology & meaning. Also update copyright with new year.
> New year new gender

- pages/accounts.html
Most accounts have new usernames, reflecting my name change to Molly. Those updated in this commit are AllPoetry, Belletristica, Bluesky, Steam, Tumblr, Twitch, Vocal Media, Wikipedia, YouTube (primary), Codeberg, itch.io and Ko-Fi.
> Update most accounts with new names

- README.md
- pages/accounts.html
- pages/contact.html
- pages/legal.html
- pages/projects/programming/github.html
- pages/projects/videos.html
- pages/projects/writing.html
- scripts/structures/footer.html
- scripts/structures/header.html
Updates GitHub account link across site with new name, as well as references to other renamed accounts.
> Update GitHub account and other references

- pages/contact.html
- pages/home.html
- pages/projects/music.html
- pages/projects/programming.html
- pages/projects/programming/github.html
- pages/projects/programming/mods.html
- pages/projects/transcribing.html
- pages/projects/videos.html
- pages/projects/writing.html
- pages/projects/writing/poetry.html
- pages/projects/writing/prose.html
- pages/projects/writing/quill.html
- scripts/modal.js
- styles/categories/decoration.css
- styles/categories/structure.css
- styles/variables.css
This changes the styling of the website to use more side-by-side text columns, tighten spacing and improve the way navigation is presented. The site should be easier to read now, uses more overt sectioning in several places, and better handles subpages.
Additionally, the Writing page has had subpages split off, and more selected poems are now included on the Poetry page. There are also minor styling changes in areas such as poem and table styling.
> Major style update

- styles/decoration.css
- styles/structure.css
- styles/widgets.css
Use nesting selector where appropriate; remove unused rules.
> CSS cleanup and improvements
